# .prettierrc or .prettierrc.yaml
$schema: 'https://json.schemastore.org/prettierrc'
embeddedLanguageFormatting: 'auto'
jsxSingleQuote: true
pugAttributeSeparator: 'as-needed'
pugSingleQuote: false
pugWrapAttributesThreshold: 1
semi: true
singleAttributePerLine: true
singleQuote: true
tabWidth: 2
trailingComma: 'es5'
useTabs: true
printWidth: 100
plugins:
  - prettier-plugin-embed
  - prettier-plugin-sql
language: 'tsql'
paramTypes: "{ named: [':'] }"
