version: "3.7"

services:
    sql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        restart: unless-stopped
        environment: 
            - "ACCEPT_EULA=Y"
            - "SA_PASSWORD=1m5ecure!"
            - "MSSQL_PID=Express"
        ports: 
            - "1433:1433"
        volumes: 
            - sqlsystem:/var/opt/mssql/
            - ./db/backups/:/backups

volumes: 
    sqlsystem: