INSERT INTO
  SECURITY.SiteAccessType
VALUES
  (4, 'All Sites');

CREATE TABLE [dbo].[PlaceTheme](
  [Id] [int] IDENTITY(1, 1) NOT NULL,
  [Category] [nvarchar](100) NOT NULL,
  [Type] [nvarchar](100) NOT NULL,
  CONSTRAINT [PK_PlaceTheme] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (
    PAD_INDEX = OFF,
    STATISTICS_NORECOMPUTE = OFF,
    IGNORE_DUP_KEY = OFF,
    ALLOW_ROW_LOCKS = ON,
    ALLOW_PAGE_LOCKS = ON
  ) ON [PRIMARY]
) ON [PRIMARY]
GO