@startuml

entity Place {
  * Id : int <<generated>>
  --
  * Category : int
  * CommunityId : int
  * CoordinateDetermination : int
  * DoorCondition : int
  * FloorCondition : int
  * PrimaryName : nvarchar
  * RoofCondition : int
  * ShowInRegister : bit
  * SiteStatus : int
  * WallCondition : int
  * YHSIId : nvarchar
  BordenNumber : nvarchar
  BuildingSize : nvarchar
  ConditionComment : nvarchar
  ContributingResources : nvarchar : <<comma delimited array>>
  Designations : nvarchar : <<comma delimited array>>
  HectareArea : nvarchar
  Latitude : nvarchar
  LocationComment : nvarchar
  LocationContext : nvarchar
  Longitude : nvarchar
  NTSMapSheet: nvarchar
  OtherCommunity : nvarchar
  OtherLocality : nvarchar
  PhysicalAddress : nvarchar
  PhysicalCountry : nvarchar
  PhysicalPostalCode : nvarchar
  PhysicalProvince : nvarchar
  PreviousAddress : nvarchar
  Records : nvarchar : <<comma delimited array>>
  ResourceType : nvarchar
  SiteCategories : nvarchar : <<comma delimited array>>
}

enum Category {
  0 : None Selected
  1 : Building
  2 : District
  3 : Place
  4 : Structure
}

enum Community {
  * Id : int <<generated>>
  --
  * Name : nvarchar
}

enum ConditionType {
  0 : Not Applicable
  1 : Fair
  2 : Good
  3 : Poor
}

entity ConstructionPeriod {
  * Id : int <<generated>>
  --
  * PlaceId : int
  * Type : int
}

enum ConstructionPeriodType {
  1 : Pre 1895
  2 : From 1896 to 1905
  3 : From 1906 to 1939
  4 : From 1940 to 1965
  5 : Post 1965
}

enum ContributingResources {
  Archaeological : Archaeological
  Building : Building
  Collection : Collection
  Landscapes : Landscapes
  Structure : Structure
}

enum CoordinateDetermination {
  1 : GPS
  2 : Paper Maps
  3 : Unknown
  4 : Digital Maps
  5 : Geocoding
}

entity Dates {
  * Id : int <<generated>>
  --
  * PlaceId : int
  * Type : int
  Details : nvarchar
  FromDate : nvarchar
  ToDate : nvarchar
}

enum DateType {
  1 : Construction
  2 : Significant Date
  8 : Construction Circa
}

enum Designations {
  Federal : Federal
  Municipal : Municipal
  Territorial : Territorial
  World : World
  NotDesignated : Not Designated
}

entity HistoricalPattern {
  * Id : int <<generated>>
  --
  * PlaceId : int
  * HistoricalPatternType : int
  Comments : nvarchar
}

enum HistoricalPatternType {
  1 : Political
  2 : Economic
  3 : Social
  4 : Geographic
}

entity Name {
  * Id : int <<generated>>
  --
  * PlaceId : int
  Description : nvarchar
}

enum Records {
  CRHP : CRHP
  WHBR : WHBR
}

enum SiteCategories {
  Architecture : Architecture
  FirstNation : First Nation
  Gravesite : Gravesite
  Industrial : Industrial
  Landscape : Landscape
}

enum SiteStatus {
  1 : Standing
  2 : Demolished
  3 : Burned
  4 : Moved
  5 : Dimantled
  6 : Reconstruction
}

Place::Category }|--o{ Category
Place::CommunityId ||--o{ Community
Place::DoorCondition }|--o{ ConditionType
Place::FloorCondition }|--o{ ConditionType
Place::RoofCondition }|--o{ ConditionType
Place::WallCondition }|--o{ ConditionType
Place }o--|| ConstructionPeriod::PlaceId
Place::ContributingResources }o--o{ ContributingResources
Place::CoordinateDetermination ||--o{ CoordinateDetermination
Place }o--|| Dates::PlaceId
Place::Designations }o--o{ Designations
Place }o--|| HistoricalPattern::PlaceId
Place }o--|| Name::PlaceId
Place::Records }o--o{ Records
Place::SiteCategories }o--o{ SiteCategories
Place::SiteStatus ||--o{ SiteStatus
HistoricalPattern::HistoricalPatternType ||--o{ HistoricalPatternType
Dates::Type ||--o{ DateType
ConstructionPeriod::Type ||--o{ ConstructionPeriodType

@enduml
