export const UserRoles = {
	ADMINISTRATOR: 'Administrator',
	SITE_ADMIN: 'Site Admin',
	SITE_EDITOR: 'Site Editor',
	SITE_VIEWER: 'Site Viewer',
	PHOTO_ADMIN: 'Photo Admin',
	PHOTO_EDITOR: 'Photo Editor',
	PHOTO_VIEWER: 'Photo Viewer',
	SITE_VIEWER_LIMITED: 'Site Viewer Limited',
	AIRPLANE_CRASH_EDITOR: 'Airplane Crash Editor',
	AIRPLANE_CRASH_VIEWER: 'Airplane Crash Viewer',
	BOATS_EDITOR: 'Boats Editor',
	PLACE_EDITOR: 'Places Editor',
	BURIALS_EDITOR: 'Burials Editor',
	PEOPLE_EDITOR: 'People Editor',
	YRHP_EDITOR: 'YRHP Editor',
	ADVANCED_MAPS: 'Advanced Mapping',
};
